FROM python:3.13-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV PIP_NO_CACHE_DIR=1

WORKDIR /app

COPY requirements.txt requirements-dev.txt ./

RUN python -m pip install --upgrade pip \
    && pip install -r requirements-dev.txt

COPY . .

CMD ["pytest"]
