# Generated by Django 5.2.17 on 2026-09-04 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='vehiclemodel',
            new_name='catalog_model_active_idx',
            old_name='catalog_model_parent_active_idx',
        ),
    ]
