# Generated by Django 5.2

import apps.catalog.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "catalog",
            "0002_rename_catalog_model_parent_active_idx_catalog_model_active_idx",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VehicleListing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "در انتظار بررسی"),
                            ("active", "فعال"),
                            ("rejected", "رد شده"),
                            ("sold", "فروخته شده"),
                            ("expired", "منقضی"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("brand_name", models.CharField(max_length=100)),
                ("model_name", models.CharField(max_length=120)),
                ("trim_name", models.CharField(blank=True, max_length=160)),
                (
                    "production_year",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1886),
                            django.core.validators.MaxValueValidator(2100),
                        ]
                    ),
                ),
                (
                    "plate_type",
                    models.CharField(
                        choices=[
                            ("free_zone", "منطقه آزاد"),
                            ("temporary_import", "واردات موقت"),
                            ("national", "پلاک ملی"),
                        ],
                        max_length=24,
                    ),
                ),
                ("free_zone", models.CharField(blank=True, max_length=80)),
                ("province", models.CharField(max_length=64)),
                ("city", models.CharField(max_length=64)),
                ("color", models.CharField(max_length=40)),
                ("body_type", models.CharField(max_length=40)),
                (
                    "engine_description",
                    models.CharField(blank=True, max_length=120),
                ),
                (
                    "transmission",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("automatic", "Automatic"),
                            ("cvt", "CVT"),
                            ("dct", "DCT"),
                            ("amt", "AMT"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "fuel_type",
                    models.CharField(
                        choices=[
                            ("gasoline", "Gasoline"),
                            ("diesel", "Diesel"),
                            ("hybrid", "Hybrid"),
                            ("phev", "Plug-in hybrid"),
                            ("electric", "Electric"),
                            ("cng", "CNG"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "drivetrain",
                    models.CharField(
                        choices=[
                            ("fwd", "Front-wheel drive"),
                            ("rwd", "Rear-wheel drive"),
                            ("awd", "All-wheel drive"),
                            ("4wd", "Four-wheel drive"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("mileage", models.PositiveIntegerField()),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("new", "آکبند"),
                            ("like_new", "در حد نو"),
                            ("clean_used", "کارکرده تمیز"),
                            ("good", "سالم"),
                            ("needs_repair", "نیاز به تعمیر"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "body_condition",
                    models.CharField(
                        choices=[
                            ("no_paint", "بدون رنگ"),
                            ("one_spot", "یک لکه رنگ"),
                            ("multiple_spots", "چند لکه رنگ"),
                            ("around_paint", "دور رنگ"),
                            ("full_paint", "تمام رنگ"),
                            ("accident", "تصادفی"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "chassis_condition",
                    models.CharField(
                        choices=[
                            ("sealed", "سالم و پلمپ"),
                            ("minor_damage", "ضربه جزئی"),
                            ("damaged", "آسیب‌دیده"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "engine_condition",
                    models.CharField(
                        choices=[
                            ("healthy", "سالم"),
                            ("needs_service", "نیاز به سرویس"),
                            ("replaced", "تعویض شده"),
                            ("needs_repair", "نیاز به تعمیر"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "insurance_months",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MaxValueValidator(12)],
                    ),
                ),
                (
                    "ownership_status",
                    models.CharField(
                        choices=[
                            ("owner", "سند به نام فروشنده"),
                            ("ready", "سند آماده انتقال"),
                            ("power_of_attorney", "وکالتی"),
                            ("financed", "در رهن یا لیزینگ"),
                        ],
                        max_length=24,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "price_type",
                    models.CharField(
                        choices=[
                            ("fixed", "قیمت قطعی"),
                            ("negotiable", "قابل مذاکره"),
                            ("contact", "تماس بگیرید"),
                        ],
                        max_length=16,
                    ),
                ),
                ("price", models.PositiveBigIntegerField(blank=True, null=True)),
                ("trade_possible", models.BooleanField(default=False)),
                ("contact_number", models.CharField(max_length=20)),
                (
                    "contact_preference",
                    models.CharField(
                        choices=[
                            ("phone", "تماس تلفنی"),
                            ("chat", "پیام در آزادگذر"),
                            ("both", "تماس و پیام"),
                        ],
                        default="both",
                        max_length=16,
                    ),
                ),
                (
                    "video",
                    models.FileField(
                        blank=True,
                        upload_to=apps.catalog.models.listing_video_upload_to,
                    ),
                ),
                ("rejection_reason", models.TextField(blank=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehicle_listings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ("-created_at", "-id")},
        ),
        migrations.CreateModel(
            name="VehicleListingImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=apps.catalog.models.listing_image_upload_to
                    ),
                ),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                ("file_size", models.PositiveIntegerField(default=0)),
                ("mime_type", models.CharField(blank=True, max_length=40)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="catalog.vehiclelisting",
                    ),
                ),
            ],
            options={"ordering": ("sort_order", "id")},
        ),
        migrations.AddIndex(
            model_name="vehiclelisting",
            index=models.Index(
                fields=["status", "-created_at"],
                name="listing_status_created_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="vehiclelisting",
            index=models.Index(
                fields=["province", "city", "status"],
                name="listing_location_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="vehiclelisting",
            index=models.Index(
                fields=["owner", "status"],
                name="listing_owner_status_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="vehiclelisting",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("price_type", "contact"),
                    ("price__isnull", False),
                    _connector="OR",
                ),
                name="listing_price_required_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="vehiclelisting",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("plate_type", "free_zone"), _negated=True),
                    models.Q(("free_zone", ""), _negated=True),
                    _connector="OR",
                ),
                name="listing_free_zone_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="vehiclelistingimage",
            constraint=models.UniqueConstraint(
                fields=("listing", "sort_order"),
                name="listing_image_order_uniq",
            ),
        ),
    ]
