# Generated by Django 5.2.16 on 2026-07-28 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('buyer', 'Buyer'), ('seller', 'Seller')], max_length=10, null=True, verbose_name='Role'),
        ),
    ]
