# Generated by Django 5.2.17 on 2026-09-05 10:13

from django.db import migrations, models


def assign_admin_role_to_superusers(apps, schema_editor) -> None:
    User = apps.get_model("accounts", "User")
    User.objects.using(schema_editor.connection.alias).filter(
        is_superuser=True,
        role__isnull=True,
    ).update(role="admin")


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_platform_roles_referrals_and_role_changes'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان تکمیل پروفایل'),
        ),
        migrations.AddField(
            model_name='user',
            name='terms_accepted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان پذیرش قوانین'),
        ),
        migrations.RunPython(
            assign_admin_role_to_superusers,
            migrations.RunPython.noop,
        ),
    ]
