# Generated by Django 5.2.17 on 2026-09-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_user_profile_completed_at_user_terms_accepted_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="OtpChallenge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone_number", models.CharField(max_length=16)),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("signup", "ثبت‌نام"),
                            ("login", "ورود"),
                            ("password_reset", "بازیابی رمز"),
                        ],
                        max_length=20,
                    ),
                ),
                ("code_hash", models.CharField(max_length=64)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("expires_at", models.DateTimeField()),
                ("cooldown_until", models.DateTimeField()),
                ("request_window_started_at", models.DateTimeField()),
                ("request_count", models.PositiveSmallIntegerField(default=1)),
                ("consumed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["expires_at"],
                        name="acct_otp_expiry_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("phone_number", "purpose"),
                        name="acct_otp_phone_purpose_uniq",
                    ),
                ],
            },
        ),
    ]
