# Generated by Django 5.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_otpchallenge"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="address",
            field=models.TextField(blank=True, verbose_name="آدرس"),
        ),
        migrations.AddField(
            model_name="user",
            name="business_description",
            field=models.TextField(blank=True, verbose_name="معرفی کسب‌وکار"),
        ),
        migrations.AddField(
            model_name="user",
            name="business_name",
            field=models.CharField(
                blank=True,
                max_length=200,
                verbose_name="نام کسب‌وکار",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="business_phone",
            field=models.CharField(
                blank=True,
                max_length=20,
                verbose_name="تلفن ثابت کسب‌وکار",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="city",
            field=models.CharField(
                blank=True,
                max_length=64,
                verbose_name="شهر",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="preferred_contact_method",
            field=models.CharField(
                choices=[
                    ("phone", "تماس تلفنی"),
                    ("chat", "پیام در آزادگذر"),
                    ("both", "تماس و پیام"),
                ],
                default="both",
                max_length=16,
                verbose_name="روش تماس ترجیحی",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="province",
            field=models.CharField(
                blank=True,
                max_length=64,
                verbose_name="استان",
            ),
        ),
    ]
